### ISSUE TITLE
mailto links are handled incorrectly

### ISSUE THREAD

**Issue by port19x** [hahwul/deadfinder#4]
Hi again.
Just tested my personal website with this and found quite a few dead links.
One false positive was on every single page tho, that being my mailto link.
This is probably because a mailto uri isn't accounted for in the `generate_url` function.

https://github.com/hahwul/deadfinder/blob/main/lib/deadfinder/utils.rb

**Comment by hahwul** [comment]
@port19x 
Thank you so much for the issue and PR! I added a few things and released it in 1.3.2.

- Github: https://github.com/hahwul/deadfinder/releases/tag/1.3.2
- Gem: https://rubygems.org/gems/deadfinder/versions/1.3.2

Enjoy your rest of day :D

**Comment by port19x** [comment]
I'm afraid I have to reopen. The url detection still seems a bit funky

![2023-08-11_09-32](https://github.com/hahwul/deadfinder/assets/82055622/3ca652e6-7b3e-4b13-967b-5f469b9a8923)

**Comment by hahwul** [comment]
@port19x 
Oh, there was such a big mistake. Github-action was referencing the old version of the image build to use. 
I just modified it and released it as a new version(1.3.3).

Please let me know if the same problem occurs with the new version! 
There was nothing unusual based on my env.

![](https://github.com/hahwul/deadfinder/assets/13212227/80a86cf4-0bc9-4d9a-9ce2-25b4b7626505)

**Comment by port19x** [comment]
Thanks

**Comment by port19x** [comment]
Can confirm it's working :+1:
